# Generated by Django 3.2.13 on 2022-06-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserveclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveSmallIntegerField(default=0)),
                ('class_num', models.PositiveSmallIntegerField(default=0)),
                ('class_type', models.PositiveSmallIntegerField(default=0)),
                ('class_select', models.PositiveSmallIntegerField(default=0)),
                ('class_title', models.CharField(default='0', max_length=100)),
                ('class_object', models.CharField(default='0', max_length=50)),
                ('class_loud', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
