# Generated by Django 3.2.13 on 2022-06-04 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(default='0', max_length=20)),
                ('teacher', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='reserveclass',
            name='class_teacher',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
