# Generated by Django 3.2.13 on 2022-06-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadda', '0002_auto_20220604_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classroom',
            field=models.CharField(default='0', max_length=20, primary_key=True, serialize=False),
        ),
    ]
